# Generated by Django 4.0.8 on 2022-10-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ext_id', models.TextField(unique=True, verbose_name='Identifier from external API')),
                ('type', models.TextField(choices=[('job', 'Job'), ('story', 'Story'), ('poll', 'Poll'), ('comment', 'Comment'), ('pollopt', 'Poll Option')], max_length=10)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('by', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('from_hn', models.BooleanField(default=False)),
                ('parent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ext_id', models.TextField(unique=True, verbose_name='Username')),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('karma', models.IntegerField()),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ext_id', models.TextField(unique=True, verbose_name='Identifier from external API')),
                ('type', models.TextField(choices=[('job', 'Job'), ('story', 'Story'), ('poll', 'Poll'), ('comment', 'Comment'), ('pollopt', 'Poll Option')], max_length=10)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('by', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('from_hn', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ext_id', models.TextField(unique=True, verbose_name='Identifier from external API')),
                ('type', models.TextField(choices=[('job', 'Job'), ('story', 'Story'), ('poll', 'Poll'), ('comment', 'Comment'), ('pollopt', 'Poll Option')], max_length=10)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('by', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('from_hn', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='topitem',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['job', 'story', 'poll', 'comment', 'pollopt'])), name='topitem_check_item_type'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'type': 'poll'}, on_delete=django.db.models.deletion.CASCADE, to='news.topitem', to_field='ext_id'),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['job', 'story', 'poll', 'comment', 'pollopt'])), name='polloption_check_item_type'),
        ),
    ]
