# Generated by Django 4.0.8 on 2022-10-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedUser',
        ),
    ]
