# Generated by Django 4.0.8 on 2022-10-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_delete_feeduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='from_hn',
            new_name='is_local',
        ),
        migrations.RenameField(
            model_name='polloption',
            old_name='from_hn',
            new_name='is_local',
        ),
        migrations.RenameField(
            model_name='topitem',
            old_name='from_hn',
            new_name='is_local',
        ),
    ]
