# Generated by Django 4.0.8 on 2022-10-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_from_hn_comment_is_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_local',
            new_name='from_hn',
        ),
        migrations.RenameField(
            model_name='polloption',
            old_name='is_local',
            new_name='from_hn',
        ),
        migrations.RenameField(
            model_name='topitem',
            old_name='is_local',
            new_name='from_hn',
        ),
    ]
