# Generated by Django 4.0.8 on 2022-10-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeduser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeduser',
            old_name='is_local',
            new_name='from_hn',
        ),
    ]
